package com.usg.apiAutomation.helpers;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.usg.apiAutomation.dtos.apiGenerationEngine.*;
import com.usg.apiAutomation.entities.postgres.apiGenerationEngine.*;
import com.usg.apiAutomation.helpers.apiEngine.ApiConversionHelper;
import com.usg.apiAutomation.helpers.apiEngine.ApiResponseHelper;
import com.usg.apiAutomation.repositories.apiGenerationEngine.*;
import com.usg.apiAutomation.utils.apiEngine.DatabaseParameterGeneratorUtil;
import com.usg.apiAutomation.utils.LoggerUtil;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;

import java.time.LocalDateTime;
import java.util.*;

@Slf4j
@RequiredArgsConstructor
public abstract class BaseApiExecutionHelper {

    protected final ApiResponseHelper responseHelper;
    protected final LoggerUtil loggerUtil;
    protected final ApiConversionHelper conversionHelper;

    public GeneratedApiEntity createAndSaveApiEntity(
            GenerateApiRequestDTO request,
            ApiSourceObjectDTO sourceObjectDTO,
            CollectionInfoDTO collectionInfo,
            String endpointPath,
            String performedBy,
            String sourceRequestId,
            GeneratedAPIRepository repository,
            ObjectMapper objectMapper,
            DatabaseParameterGeneratorUtil parameterGenerator,
            ApiConversionHelper conversionHelper,
            String databaseType) {

        GeneratedApiEntity api = new GeneratedApiEntity();

        // REMOVE THIS LINE - Don't set ID manually
        // api.setId(UUID.randomUUID().toString());

        // Set basic fields (ID will be generated by Hibernate)
        api.setApiName(request.getApiName());
        api.setApiCode(request.getApiCode());
        api.setDescription(request.getDescription());
        api.setVersion(request.getVersion());
        api.setHttpMethod(request.getHttpMethod());
        api.setBasePath(request.getBasePath());
        api.setEndpointPath(endpointPath);
        api.setStatus(request.getStatus() != null ? request.getStatus() : "DRAFT");
        api.setIsActive(true);
        api.setCategory(request.getCategory());
        api.setTags(request.getTags() != null ? request.getTags() : new ArrayList<>());
        api.setCreatedAt(LocalDateTime.now());
        api.setCreatedBy(performedBy);
        api.setUpdatedAt(LocalDateTime.now());
        api.setUpdatedBy(performedBy);
        api.setOwner(performedBy);
        api.setTotalCalls(0L);

        // CRITICAL: Set database type
        api.setDatabaseType(databaseType);

        // Store source object info as Map
        if (sourceObjectDTO != null) {
            try {
                Map<String, Object> sourceObjectMap = objectMapper.convertValue(
                        sourceObjectDTO,
                        new com.fasterxml.jackson.core.type.TypeReference<Map<String, Object>>() {});
                api.setSourceObjectInfo(sourceObjectMap);
            } catch (Exception e) {
                log.error("Error converting source object to map", e);
            }
        }

        // Store collection info as Map
        if (collectionInfo != null) {
            try {
                Map<String, Object> collectionInfoMap = objectMapper.convertValue(
                        collectionInfo,
                        new com.fasterxml.jackson.core.type.TypeReference<Map<String, Object>>() {});
                api.setCollectionInfo(collectionInfoMap);
            } catch (Exception e) {
                log.error("Error converting collection info to map", e);
            }
        }

        api.setSourceRequestId(sourceRequestId);

        // Set up relationships
        setupApiRelationships(api, request, sourceObjectDTO, parameterGenerator, conversionHelper);

        // Let Hibernate generate the ID
        GeneratedApiEntity savedApi = repository.save(api);
        log.info("Created API entity with ID: {}, Database Type: {}", savedApi.getId(), savedApi.getDatabaseType());

        return savedApi;
    }

    public GeneratedApiEntity getApiEntity(GeneratedAPIRepository repository, String apiId) {
        return repository.findById(apiId)
                .orElseThrow(() -> new RuntimeException("API not found: " + apiId));
    }

    /**
     * Update API entity with new data
     */
    public void updateApiEntity(GeneratedApiEntity api,
                                GenerateApiRequestDTO request,
                                ApiSourceObjectDTO sourceObjectDTO,
                                CollectionInfoDTO collectionInfo,
                                String performedBy) {

        api.setApiName(request.getApiName());
        api.setApiCode(request.getApiCode());
        api.setDescription(request.getDescription());
        api.setVersion(request.getVersion());
        api.setStatus(request.getStatus() != null ? request.getStatus() : api.getStatus());
        api.setHttpMethod(request.getHttpMethod());
        api.setBasePath(request.getBasePath());
        api.setEndpointPath(request.getEndpointPath());
        api.setCategory(request.getCategory());
        api.setOwner(request.getOwner());
        api.setUpdatedAt(LocalDateTime.now());
        api.setUpdatedBy(performedBy);

        if (request.getTags() != null) {
            api.setTags(request.getTags());
        }

        // Preserve database type - DO NOT change it!
        // api.setDatabaseType() - intentionally commented to preserve original

        if (sourceObjectDTO != null) {
            try {
                Map<String, Object> sourceObjectMap = new HashMap<>();
                sourceObjectMap.put("objectName", sourceObjectDTO.getObjectName());
                sourceObjectMap.put("objectType", sourceObjectDTO.getObjectType());
                sourceObjectMap.put("owner", sourceObjectDTO.getOwner());
                sourceObjectMap.put("OWNER", sourceObjectDTO.getOwner());  // Add uppercase version
                sourceObjectMap.put("schemaName", sourceObjectDTO.getSchemaName());
                sourceObjectMap.put("SchemaName", sourceObjectDTO.getSchemaName());  // Add original case
                sourceObjectMap.put("SCHEMA_NAME", sourceObjectDTO.getSchemaName());  // Add uppercase underscore version
                sourceObjectMap.put("operation", sourceObjectDTO.getOperation());
                sourceObjectMap.put("databaseType", sourceObjectDTO.getDatabaseType());

                // Add synonym info if present
                if (sourceObjectDTO.getIsSynonym() != null) {
                    sourceObjectMap.put("isSynonym", sourceObjectDTO.getIsSynonym());
                    sourceObjectMap.put("targetType", sourceObjectDTO.getTargetType());
                    sourceObjectMap.put("targetName", sourceObjectDTO.getTargetName());
                    sourceObjectMap.put("targetOwner", sourceObjectDTO.getTargetOwner());
                }

                api.setSourceObjectInfo(sourceObjectMap);
            } catch (Exception e) {
                log.error("Error converting source object to map", e);
            }
        }

        if (collectionInfo != null) {
            try {
                ObjectMapper objectMapper = new ObjectMapper();
                Map<String, Object> collectionInfoMap = objectMapper.convertValue(
                        collectionInfo,
                        new com.fasterxml.jackson.core.type.TypeReference<Map<String, Object>>() {});
                api.setCollectionInfo(collectionInfoMap);
            } catch (Exception e) {
                log.error("Error converting collection info to map", e);
            }
        }

        log.info("Updated API entity: {}, Preserving database type: {}", api.getId(), api.getDatabaseType());
    }

    /**
     * Clear all relationships from the API entity
     */
    public void clearApiRelationships(GeneratedApiEntity api) {
        if (api == null) return;

        log.debug("Clearing relationships for API: {}", api.getId());

        // Clear one-to-one relationships (setting to null is fine)
        api.setSchemaConfig(null);
        api.setAuthConfig(null);
        api.setRequestConfig(null);
        api.setResponseConfig(null);
        api.setSettings(null);

        // Clear collections by modifying the existing ones
        if (api.getParameters() != null) {
            api.getParameters().clear();  // Clear the existing collection
        }
        if (api.getResponseMappings() != null) {
            api.getResponseMappings().clear();  // Clear the existing collection
        }
        if (api.getHeaders() != null) {
            api.getHeaders().clear();  // Clear the existing collection
        }
        if (api.getTests() != null) {
            api.getTests().clear();  // Clear the existing collection
        }

        log.debug("Successfully cleared relationships for API: {}", api.getId());
    }

    /**
     * Recreate all relationships for the API entity
     */
    public void recreateApiRelationships(GeneratedApiEntity api,
                                         GenerateApiRequestDTO request,
                                         ApiSourceObjectDTO sourceObjectDTO,
                                         DatabaseParameterGeneratorUtil parameterGenerator,
                                         ApiConversionHelper conversionHelper) {

        log.debug("Recreating relationships for API: {}", api.getId());

        // IMPORTANT: Make sure collections are initialized
        if (api.getParameters() == null) {
            api.setParameters(new ArrayList<>());
        }
        if (api.getHeaders() == null) {
            api.setHeaders(new ArrayList<>());
        }
        if (api.getResponseMappings() == null) {
            api.setResponseMappings(new ArrayList<>());
        }
        if (api.getTests() == null) {
            api.setTests(new ArrayList<>());
        }

        // Recreate relationships using the setup method
        setupApiRelationships(api, request, sourceObjectDTO, parameterGenerator, conversionHelper);

        log.debug("Successfully recreated relationships for API: {}", api.getId());
    }

    /**
     * Prepare validated request for execution
     */
    public ExecuteApiRequestDTO prepareValidatedRequest(GeneratedApiEntity api, ExecuteApiRequestDTO executeRequest) {
        if (executeRequest == null) {
            executeRequest = new ExecuteApiRequestDTO();
        }

        // Ensure request has ID
        if (executeRequest.getRequestId() == null) {
            executeRequest.setRequestId(UUID.randomUUID().toString());
        }

        // Set URL if not present
        if (executeRequest.getUrl() == null && api.getBasePath() != null && api.getEndpointPath() != null) {
            executeRequest.setUrl(api.getBasePath() + api.getEndpointPath());
        }

        return executeRequest;
    }

    /**
     * Log execution to database
     */
    public void logExecution(ApiExecutionLogRepository logRepository, GeneratedApiEntity api,
                             ExecuteApiRequestDTO request, Object response, int statusCode,
                             long executionTime, String performedBy, String clientIp,
                             String userAgent, String errorMessage, ObjectMapper objectMapper) {
        try {
            // Build the log entity WITHOUT setting ID manually
            ApiExecutionLogEntity logEntity = ApiExecutionLogEntity.builder()
                    // Don't set ID - let Hibernate generate it
                    .executedAt(LocalDateTime.now())
                    .executedBy(performedBy)
                    .executionTimeMs(executionTime)
                    .responseStatus(statusCode)
                    .clientIp(clientIp)
                    .userAgent(userAgent)
                    .errorMessage(errorMessage)
                    .build();

            // Set the bidirectional relationship
            if (api != null) {
                logEntity.setGeneratedApi(api);
            }

            // Process request data
            if (request != null) {
                logEntity.setRequestId(request.getRequestId());

                // Convert request params to Map
                if (request.getPathParams() != null || request.getQueryParams() != null || request.getHeaders() != null) {
                    Map<String, Object> requestParams = new HashMap<>();
                    if (request.getPathParams() != null) requestParams.put("pathParams", request.getPathParams());
                    if (request.getQueryParams() != null) requestParams.put("queryParams", request.getQueryParams());
                    if (request.getHeaders() != null) requestParams.put("headers", request.getHeaders());
                    if (request.getUrl() != null) requestParams.put("url", request.getUrl());
                    if (request.getHttpMethod() != null) requestParams.put("httpMethod", request.getHttpMethod());
                    logEntity.setRequestParams(requestParams);
                }

                // Convert request body to Map
                if (request.getBody() != null) {
                    try {
                        if (request.getBody() instanceof Map) {
                            logEntity.setRequestBody((Map<String, Object>) request.getBody());
                        } else {
                            Map<String, Object> bodyMap = new HashMap<>();
                            bodyMap.put("value", request.getBody());
                            logEntity.setRequestBody(bodyMap);
                        }
                    } catch (Exception e) {
                        log.warn("Failed to convert request body to map: {}", e.getMessage());
                        Map<String, Object> errorBody = new HashMap<>();
                        errorBody.put("error", "Failed to serialize body");
                        errorBody.put("type", request.getBody().getClass().getSimpleName());
                        logEntity.setRequestBody(errorBody);
                    }
                }
            }

            // Convert response to Map
            if (response != null) {
                try {
                    if (response instanceof Map) {
                        logEntity.setResponseBody((Map<String, Object>) response);
                    } else {
                        Map<String, Object> responseMap = new HashMap<>();
                        responseMap.put("value", response);
                        logEntity.setResponseBody(responseMap);
                    }
                } catch (Exception e) {
                    log.warn("Failed to convert response to map: {}", e.getMessage());
                    Map<String, Object> errorResponse = new HashMap<>();
                    errorResponse.put("error", "Failed to serialize response");
                    errorResponse.put("type", response.getClass().getSimpleName());
                    logEntity.setResponseBody(errorResponse);
                }
            }

            // Save the log entity - let Hibernate generate the ID
            try {
                logRepository.save(logEntity);
                log.debug("Execution log saved successfully with ID: {}", logEntity.getId());
            } catch (org.springframework.orm.ObjectOptimisticLockingFailureException e) {
                // For optimistic locking failures, just log the error and continue
                // Don't retry - let Hibernate handle it on next attempt
                log.warn("Optimistic locking failure for execution log (non-critical): {}", e.getMessage());
            } catch (Exception e) {
                // Log the error but don't throw - logging should not break the main flow
                log.error("Failed to save execution log (non-critical): {}", e.getMessage(), e);
            }

        } catch (Exception e) {
            // Catch all to ensure logging failure doesn't affect the main transaction
            log.error("Error in logExecution (non-critical): {}", e.getMessage(), e);
        }
    }

    /**
     * Update API statistics after execution
     */
    public void updateApiStats(GeneratedApiEntity api, GeneratedAPIRepository repository) {
        if (api != null) {
            api.setTotalCalls(api.getTotalCalls() != null ? api.getTotalCalls() + 1 : 1);
            api.setLastCalledAt(LocalDateTime.now());
            repository.save(api);
        }
    }

    /**
     * Save test result
     */
    public ApiTestEntity saveTestResult(ApiTestRepository testRepository, GeneratedApiEntity api,
                                        ApiTestRequestDTO testRequest, ExecuteApiResponseDTO executionResult,
                                        boolean passed, long executionTime, String performedBy,
                                        ObjectMapper objectMapper) {

        // Create test data map from request
        Map<String, Object> testData = new HashMap<>();
        if (testRequest.getPathParams() != null) testData.put("pathParams", testRequest.getPathParams());
        if (testRequest.getQueryParams() != null) testData.put("queryParams", testRequest.getQueryParams());
        if (testRequest.getHeaders() != null) testData.put("headers", testRequest.getHeaders());
        if (testRequest.getBody() != null) testData.put("body", testRequest.getBody());

        // Prepare expected response
        Map<String, Object> expectedResponse = new HashMap<>();
        if (testRequest.getExpectedResponse() != null) {
            if (testRequest.getExpectedResponse() instanceof Map) {
                expectedResponse = (Map<String, Object>) testRequest.getExpectedResponse();
            } else {
                expectedResponse.put("value", testRequest.getExpectedResponse());
            }
        }

        // Prepare actual response
        Map<String, Object> actualResponse = new HashMap<>();
        if (executionResult.getData() != null) {
            if (executionResult.getData() instanceof Map) {
                actualResponse = (Map<String, Object>) executionResult.getData();
            } else {
                actualResponse.put("value", executionResult.getData());
            }
        }

        // Prepare execution results
        Map<String, Object> executionResults = new HashMap<>();
        executionResults.put("responseCode", executionResult.getResponseCode());
        executionResults.put("success", executionResult.getSuccess());
        executionResults.put("message", executionResult.getMessage());
        executionResults.put("passed", passed);

        // Build the test entity
        ApiTestEntity test = ApiTestEntity.builder()
                .id(UUID.randomUUID().toString())
                .testName(testRequest.getTestName())
                .testType(testRequest.getTestType() != null ? testRequest.getTestType() : "UNIT")
                .status(passed ? "PASSED" : "FAILED")
                .executionTimeMs(executionTime)
                .executedAt(LocalDateTime.now())
                .executedBy(performedBy)
                .testData(testData)
                .expectedResponse(expectedResponse)
                .actualResponse(actualResponse)
                .executionResults(executionResults)
                // Set default test configuration flags
                .testConnection(true)
                .testObjectAccess(true)
                .testDataTypes(true)
                .testQueryPerformance(true)
                .testSQLInjection(true)
                .testAuthentication(true)
                .testAuthorization(true)
                .build();

        // Set the bidirectional relationship
        test.setGeneratedApi(api);

        return testRepository.save(test);
    }

    // Abstract method for database-specific relationship setup
    protected abstract void setupApiRelationships(GeneratedApiEntity api,
                                                  GenerateApiRequestDTO request,
                                                  ApiSourceObjectDTO sourceObjectDTO,
                                                  DatabaseParameterGeneratorUtil parameterGenerator,
                                                  ApiConversionHelper conversionHelper);

    // Abstract method for database-specific execution
    public abstract Object executeAgainstDatabase(GeneratedApiEntity api,
                                                  ApiSourceObjectDTO sourceObject,
                                                  ExecuteApiRequestDTO validatedRequest,
                                                  List<ApiParameterDTO> configuredParamDTOs);
}